#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jan 12 04:23:27 CET 2025
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim morse_decoder_top_tb_behav -key {Behavioral:sim_1:Functional:morse_decoder_top_tb} -tclbatch morse_decoder_top_tb.tcl -log simulate.log"
xsim morse_decoder_top_tb_behav -key {Behavioral:sim_1:Functional:morse_decoder_top_tb} -tclbatch morse_decoder_top_tb.tcl -log simulate.log

