#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Jan 11 23:52:04 CET 2025
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4d28023f245f4957829ea4bab48f5835 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot morse_decoder_top_tb_func_impl xil_defaultlib.morse_decoder_top_tb -log elaborate.log"
xelab -wto 4d28023f245f4957829ea4bab48f5835 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot morse_decoder_top_tb_func_impl xil_defaultlib.morse_decoder_top_tb -log elaborate.log

